version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8001:8001"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
